"""protocols

Revision ID: 3f5221b66e15
Revises: 9474324542c6
Create Date: 2017-06-08 15:48:29.235630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5221b66e15'
down_revision = '9474324542c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('protocol_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('decision_id', sa.String(length=16), nullable=False),
    sa.Column('decision_num', sa.Integer(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision')
    op.drop_table('protocol')
    # ### end Alembic commands ###
