"""protocol_txt

Revision ID: 6ac75c2f3859
Revises: d73f52ce9c7b
Create Date: 2017-07-31 14:27:39.573325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac75c2f3859'
down_revision = 'd73f52ce9c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocol', sa.Column('protocol_txt', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocol', 'protocol_txt')
    # ### end Alembic commands ###
