"""resolutions

Revision ID: d73f52ce9c7b
Revises: db15cfe36c2a
Create Date: 2017-07-19 11:43:13.042599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73f52ce9c7b'
down_revision = 'db15cfe36c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('resolution_id', sa.String(length=16), nullable=False),
    sa.Column('resolution_num', sa.Integer(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolution')
    # ### end Alembic commands ###
