"""empty message

Revision ID: db15cfe36c2a
Revises: 20fd862edf9b
Create Date: 2017-06-13 16:22:17.590014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db15cfe36c2a'
down_revision = '20fd862edf9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision', sa.Column('decision_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decision', 'decision_date')
    # ### end Alembic commands ###
